#define FMP_TOKEN_AND                              1
#define FMP_TOKEN_OR                               2
#define FMP_TOKEN_EQ                               3
#define FMP_TOKEN_NEQ                              4
#define FMP_TOKEN_GT                               5
#define FMP_TOKEN_GEQ                              6
#define FMP_TOKEN_LT                               7
#define FMP_TOKEN_LEQ                              8
#define FMP_TOKEN_ADD                              9
#define FMP_TOKEN_SUB                             10
#define FMP_TOKEN_MUL                             11
#define FMP_TOKEN_DIV                             12
#define FMP_TOKEN_MOD                             13
#define FMP_TOKEN_POW                             14
#define FMP_TOKEN_NOT                             15
#define FMP_TOKEN_BRA                             16
#define FMP_TOKEN_KET                             17
#define FMP_TOKEN_INT                             18
#define FMP_TOKEN_FLT                             19
#define FMP_TOKEN_STR                             20
#define FMP_TOKEN_VEC                             21
#define FMP_TOKEN_MAT                             22
#define FMP_TOKEN_INTARG                          23
#define FMP_TOKEN_FLTARG                          24
#define FMP_TOKEN_STRARG                          25
#define FMP_TOKEN_VECARG                          26
#define FMP_TOKEN_MATARG                          27
#define FMP_TOKEN_LPAR                            28
#define FMP_TOKEN_RPAR                            29
#define FMP_TOKEN_FUNC                            30
#define FMP_TOKEN_COM                             31
